### ISSUE TITLE
TSX Todo and JSDOC Params not highlighted

### ISSUE THREAD

**Issue by danielnehrig** [tree-sitter/tree-sitter-typescript#157]
On a TSX file the JSDOC params are not highlighted

example:
```tsx
/**
 * TODO im not highlighted
 * @see im also not highlighted
 * @param not highlighted :(
 */
const Component = () => {
 return <>broken</>
}
```

**Comment by danielnehrig** [comment]
https://github.com/tree-sitter/tree-sitter-typescript/issues/136

related

**Comment by mjambon** [comment]
[Comments are not parsed](https://github.com/tree-sitter/tree-sitter-javascript/blob/a263a8f53266f8f0e47e21598e488f0ef365a085/grammar.js#L893-L900) at the moment, which is why there's no highlighting in your editor. The typescript and tsx grammars extend the [javascript grammar](https://github.com/tree-sitter/tree-sitter-javascript) and would inherit how comments are parsed.

I'm not going to implement it myself because I'm here for features that benefit [semgrep](https://github.com/returntocorp/semgrep), but if you or someone else want to add it, PRs are welcome.

**Comment by maxbrunsfeld** [comment]
@danielnehrig Are you referring to a behavior in Neovim? I think yo should open a Neovim issue. There is this parser that Neovim can use to parse doc comments: https://github.com/tree-sitter/tree-sitter-jsdoc.
