### ISSUE TITLE
TypeScript requires function params to have type annotations

### ISSUE THREAD

**Issue by kevinbarabash** [tree-sitter/tree-sitter-typescript#223]
The following piece of code is not valid TypeScript but `tree-sitter-typescript` parses without any errors:

```typescript
const add = (a, b) => a + b;
```

Here's a link to the TypeScript Playground showing that the snippet above is valid JavaScript or TypeScript:
https://www.typescriptlang.org/play?ssl=1&ssc=29&pln=1&pc=1#code/MYewdgzgLgBAhgEwTAvDAFHANDARgSlQD54YBqPAbiA

The output of `tree-sitter parse` is the following:

```
[program](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [1, 0]
  [lexical_declaration](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [0, 28]
    [variable_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [0, 6] - [0, 27]
      name: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 6] - [0, 9]
      value: [arrow_function](https://tree-sitter.github.io/tree-sitter/playground#) [0, 12] - [0, 27]
        parameters: [formal_parameters](https://tree-sitter.github.io/tree-sitter/playground#) [0, 12] - [0, 18]
          [required_parameter](https://tree-sitter.github.io/tree-sitter/playground#) [0, 13] - [0, 14]
            pattern: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 13] - [0, 14]
          [required_parameter](https://tree-sitter.github.io/tree-sitter/playground#) [0, 16] - [0, 17]
            pattern: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 16] - [0, 17]
        body: [binary_expression](https://tree-sitter.github.io/tree-sitter/playground#) [0, 22] - [0, 27]
          left: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 22] - [0, 23]
          right: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 26] - [0, 27]
```

I was expecting there to be two `ERROR` nodes, one after each `required_parameter` node.

**Comment by hendrikvanantwerpen** [comment]
Hi @kevinbarabash!

Deciding what is a valid TypeScript program is a combination of what is accepted by the grammar (which is by definition context-free), and possible follow-up analysis, such as resolving names, checking and infering types and possible more (which are context sensitive).

The error that is reported is not a grammar issue, but a type checking issue. For example, the following program is accepted, even though the lambda expression is exactly the same as in your example:

```
const add: (x: number, y: number) => number = (a, b) => a + b;
```

The reported error was because TypeScript could not infer the type of the parameters, but that information can come from many places. A type annotation on the parameter itself is just one of them. This is not something that can be encoded in the grammar. The error is also not a hard error, it is controlled by the `noImplicitAny` compiler flag.

**Comment by kevinbarabash** [comment]
That makes sense.  I keep forgetting that TS does infer functions, but only through their uses.
