### ISSUE TITLE
Optional chaining is not supported

### ISSUE THREAD

**Issue by steelsojka** [tree-sitter/tree-sitter-typescript#80]
This was introduced in TS3.7 (and javascript... not sure which spec version).

```typescript
test?.value
```

```
program [0, 0] - [1, 0])
  expression_statement [0, 0] - [0, 11])
    member_expression [0, 0] - [0, 11])
      object: identifier [0, 0] - [0, 4])
      ERROR [0, 4] - [0, 5])
      property: property_identifier [0, 6] - [0, 11])
```

Is this on the road map?

**Comment by maxbrunsfeld** [comment]
Yes, we should definitely add support for this. Thanks for the report.

**Comment by steelsojka** [comment]
This should probably move to javascript since it's a javascript feature as well.

**Comment by mjambon** [comment]
This is the most common parsing errors I see on popular typescript repos (around half of the errors).

My understanding is that it's an official typescript feature since 2019 but only in the ecmascript 2020 draft. It appears to be supported by chrome but not sure about wider support, so that would explain why we often see the problem with typescript but not javascript.

I'll give it a shot.

**Comment by mjambon** [comment]
@steelsojka optional chaining is now supported, for both javascript and typescript.
