### ISSUE TITLE
Disable automatic colon insertion before function body

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter-typescript#95]
This is something I noticed while testing the fix for https://github.com/tree-sitter/tree-sitter-typescript/issues/93.

The following code is parsed correctly by tree-sitter-javascript parser but incorrectly by tree-sitter-typescript:
```typescript
function f()
{}
```

tree-sitter-typescript sees a `function_signature` followed by a `statement_block`:
```
(program [0, 0] - [2, 0]
  (function_signature [0, 0] - [0, 12]
    name: (identifier [0, 9] - [0, 10])
    parameters: (formal_parameters [0, 10] - [0, 12]))
  (statement_block [1, 0] - [1, 2]))
```

However, the tree-sitter-javascript implementation works fine and gives us a single `function_declaration`:
```
(program [0, 0] - [2, 0]
  (function_declaration [0, 0] - [1, 2]
    name: (identifier [0, 9] - [0, 10])
    parameters: (formal_parameters [0, 10] - [0, 12])
    body: (statement_block [1, 0] - [1, 2])))
```

**Comment by maxbrunsfeld** [comment]
Yeah, this fix will be slightly more complex than the one for `:` tokens, because an automatic semicolon can *sometimes* appear before a `{`, but not in this specific state.

The external scanner's `scan` function [gets passed](https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners) an array of booleans that tell it which tokens are currently valid. So we'll have to figure out a way of differentiating between the two cases based on the *validity* of a certain token.

You can add any token to the `externals` array in order to have that token's validity passed to the external scanner as an additional boolean. We have already done something like this [here](https://github.com/tree-sitter/tree-sitter-typescript/blob/73afadbd117a8e8551758af9c3a522ef46452119/common/define-grammar.js#L29-L36).

**Comment by maxbrunsfeld** [comment]
One idea: maybe we should add `:` to that array, so that the external scanner will be able to tell if a type annotation (e.g. `: T`) is currently valid. Then the external scanner could *avoid* creating an automatic semicolon if a type annotation is valid in the current state.

**Comment by resolritter** [comment]
Adding more context to this which might already be obvious for the participants, but it was unclear to me.

Going by the [Declaration Reference](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html) and [this snippet](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA7KBbEBnADlMCUE8AZASwCN4BvAKHngDMBXRMAF2IHtF4UoBrEAOJwQbRAHMAFOgBc8dCxjFxASgDcNSgF8q2qqEiwEjZm07c+g4aMky5CpWLVUKmoA) in the TypeScript playground, `function f()` is only considere a signature declaration inside of namespace declarations (`declare namespace ...`). Outside of them, the statement needs to be started with `declare` in order to be considered a declaration. This is true even for top-level signatures on declaration files (i.e. `.d.ts`).

Is it fair to state that this ambiguity would be solved if there's a check for: "the statement is inside of a namespace declaration's block scope"? Or are there more contexts where `function f()` can mean a signature without the `declare` keyword upfront?

If looking at the scope is enough, then I can see some piece of state (like the [tags state](https://github.com/tree-sitter/tree-sitter-html/blob/7f442e1c6163d450c69c75c7a621badc3a0ea98f/src/scanner.cc#L278)) working here, only it'd be `namespace_scope_count` (since namespaces can nest arbitrarily inside of namespaces). Checking if `namespace_scope_count == 0` would disambiguate between declaration and signature.
